I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 73, in script
    narrator "Start"
  File "game/script.rpy", line 73, in script
    narrator "Start"
TypeError: missing a required argument: 'name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\main.py", line 637, in main
    run(restart)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/script.rpy", line 73, in script
    narrator "Start"
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 73, in script
    narrator "Start"
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\exports.py", line 1494, in say
    who(what, *args, **kwargs)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\character.py", line 1394, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\character.py", line 1045, in do_display
    display_say(who,
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\character.py", line 741, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 2166, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 2688, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 2688, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\parameter.py", line 429, in apply_arguments
    return parameters.apply(args or (), kwargs or {}, ignore_errors)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\parameter.py", line 283, in apply
    raise TypeError(msg) # from None
TypeError: missing a required argument: 'name'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Galactic Heart 1.0
Sun Aug  4 02:00:19 2024
