I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 288, in script
    soldier"Routine reports? You expect us to believe you just stumbled upon classified material by accident?"
Exception: Sayer 'soldier' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 288, in script
    soldier"Routine reports? You expect us to believe you just stumbled upon classified material by accident?"
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'soldier' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Galactic Heart 1.0
Sun Aug  4 16:58:15 2024
